export const archive = [
    {
        id: "1",
        year: "2024",
        name: "Stocks diary",
        techStack: [
            "React",
            "TypeScript",
            "Tailwind CSS",
            "Express.js",
            "Mongoose",
            "MongoDB",
            "JWT",
        ],
        link: "https://stocks-diary-one-beta.vercel.app",
    },
    {
        id: "2",
        year: "2024",
        name: "Apple iPhone 15 Pro page",
        techStack: ["React", "Tailwind CSS", "GSAP", "Three.js"],
        link: "https://apple-clone-one-beta.vercel.app",
    },
    {
        id: "3",
        year: "2024",
        name: "AI Photo Editor",
        techStack: [
            "Next.js",
            "TypeScript",
            "Tailwind CSS",
            "MongoDB",
            "Clerk",
            "Cloudinary API",
        ],
        link: "https://ai-photo-editor-khaki.vercel.app",
    },
    {
        id: "4",
        year: "2023",
        name: "Twitter clone T3 App",
        techStack: [
            "Next.js",
            "TypeScript",
            "Tailwind CSS",
            "tRPC",
            "Prisma",
            "Postgresql",
        ],
        link: "https://twitter-clone-lyart-kappa-79.vercel.app",
    },
    {
        id: "5",
        year: "2023",
        name: "Blog project",
        techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Firebase"],
        link: "https://blog-kohl-six-29.vercel.app",
    },
];
